name: Build and deploy Python app to Azure Web App - BijliAudit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_70D162D904DF415291CC8667B27E578F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A2CE1F92EA8146E492F07A3BF9D566F3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_42DC7A7708794D85A2E364DFAFB83B19 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BijliAudit'
          slot-name: 'Production'
          package: './bijli-audit-backend'
